name: Build, Test & Generate Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-generate-docs:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Doxygen
        run: |
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_17_0/doxygen-1.17.0.linux.bin.tar.gz
          tar -xzf doxygen-1.17.0.linux.bin.tar.gz
          sudo cp doxygen-1.17.0/bin/doxygen /usr/local/bin/

      - name: Install Graphviz
        run: |
          wget https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/15.0.0/ubuntu_24.04_graphviz-15.0.0-cmake.deb
          sudo dpkg -i ubuntu_24.04_graphviz-15.0.0-cmake.deb

      - name: Installing dependencies...
        run: dotnet restore

      - name: Building...
        run: dotnet build --configuration Release --no-restore

      - name: Running test...
        run: dotnet test --configuration Release --no-build

      - name: Generating docs...
        working-directory: docs
        run: doxygen Doxyfile
        continue-on-error: false
